// Code generated by goctl. DO NOT EDIT.
package types

type TsReq struct {
	OrderSn     string `json:"orderSn"`
	ServiceType string `json:"serviceType"`
}

type TsResp struct {
	Msg string `json:"msg"`
}
