// Code generated by goctl. DO NOT EDIT!
// Source: test.proto

package server

import (
	"context"

	"looklook/app/test/cmd/rpc/internal/logic"
	"looklook/app/test/cmd/rpc/internal/svc"
	"looklook/app/test/cmd/rpc/pb"
)

type TestServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTestServer
}

func NewTestServer(svcCtx *svc.ServiceContext) *TestServer {
	return &TestServer{
		svcCtx: svcCtx,
	}
}

func (s *TestServer) Testac(ctx context.Context, in *pb.TsReq) (*pb.TsResp, error) {
	l := logic.NewTestacLogic(ctx, s.svcCtx)
	return l.Testac(in)
}
