// Code generated by goctl. DO NOT EDIT!
// Source: test.proto

package test

import (
	"context"

	"looklook/app/test/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginReq = pb.LoginReq
	TsReq    = pb.TsReq
	TsResp   = pb.TsResp

	Test interface {
		Testac(ctx context.Context, in *TsReq, opts ...grpc.CallOption) (*TsResp, error)
	}

	defaultTest struct {
		cli zrpc.Client
	}
)

func NewTest(cli zrpc.Client) Test {
	return &defaultTest{
		cli: cli,
	}
}

func (m *defaultTest) Testac(ctx context.Context, in *TsReq, opts ...grpc.CallOption) (*TsResp, error) {
	client := pb.NewTestClient(m.cli.Conn())
	return client.Testac(ctx, in, opts...)
}
